### ISSUE TITLE
did your laptop can't map caplock to ctlr key 

### ISSUE THREAD

**Issue by seyhadot** [ErrorErrorError/msi-gs65-gs75-hackintosh#1]
i have try to map caplock key to ctrl in my MSI GS658SE but it's doestn't work do you know how to make it work?

**Comment by ErrorErrorError** [comment]
You want to switch the caps lock to ctrl? May I ask why would you want that? Just out of curiosity.

**Comment by erikbdev** [comment]
- @seyhadot you will have to first disassemble the SSDT-KEYS.aml to .dsl and then figure out the ADB maps and PS2 scans of the caps lock and ctrl.  Follow this guide to figure out the ADB and ps2 scans. Once you got it. For each key I can help you with the ssdt patching.
 https://github.com/RehabMan/OS-X-Voodoo-PS2-Controller/wiki/How-to-Use-Custom-Keyboard-Mapping

**Comment by seyhadot** [comment]
for dissassemble we use F4 in clover right ? sorry i am new in hackintosh

**Comment by erikbdev** [comment]
[SSDT-KEYS.zip](https://github.com/ErrorErrorError/msi-gs65-gs75-hackintosh/files/3659081/SSDT-KEYS.zip)
Use this version instead of the one that's uploaded on github. Make sure you have it on /EFI/Clover/ACPI/Patched/. 

If you keep having issues let me know.
