### ISSUE TITLE
Link to compatible Wifi Card

### ISSUE THREAD

**Issue by mtotallywired** [ErrorErrorError/msi-gs65-gs75-hackintosh#11]
BCM94352Z

Hi there, I have a GS65 Stealth with 2060 and 8th Gen i7 incoming...and I'd like to purchase the compatible wifi card for wifi and bluetooth compatibility. You mention the BCM94352Z, but can you please link me to the version you bought? When I do a search there seem to be various versions with different key shapes. 

Thanks so much in advance. Hope this is easy to answer.

**Comment by erikbdev** [comment]
Hey,

I bought the Dell DW1560 M.2 (NGFF). I bought it on ebay a few years ago for about $35. I can't find the link of the seller who I bought from, presumably they sold out, but I'm sure they're still selling them on eBay.

**Comment by mtotallywired** [comment]
Thanks so much for your prompt reply. 
Does it happen to look like this? key shape has 3 slits (sorry I don't know how better to describe it) 
https://ebay.us/XIf4sc

They seem quite expensive now and mostly all from China. If I didn't want to wait and okay with taking up 2 of my usb 3 slots, could I feasibly just use a wifi and bluetooth dongle?

**Comment by erikbdev** [comment]
> Does it happen to look like this? key shape has 3 slits (sorry I don't know how better to describe it)

Yes, that's an M.2 (NGFF) sloth, so it should fit your laptop.



> They seem quite expensive now and mostly all from China. If I didn't want to wait and okay with taking up 2 of my usb 3 slots, could I feasibly just use a wifi and bluetooth dongle?

You should be able to use a USB WiFi and bluetooth dongle too if you'd rather take that route.

**Comment by mtotallywired** [comment]
You are awesome. Thanks for the clarification! I know this is unrelated in this thread but last question is does thunderbolt port work in your hackintosh on the gs65?

**Comment by erikbdev** [comment]
> does thunderbolt port work in your hackintosh on the gs65

I mean I guess it depends on how you use it. For instance, if you use it as a eGPU, then I think it wont work as of yet since I can't test it, but you can hook up TB to HDMI adapter and it works fine.
