### ISSUE TITLE
Installer reboot at internet configuration

### ISSUE THREAD

**Issue by WaKeNighTt** [ErrorErrorError/msi-gs65-gs75-hackintosh#12]
Hi first thanks for the awesome guide ! 
I have a MSI GS6 stealth , who have almost the same hardware as you.
I've successfully installed Mojave at the first part but when i need to configure the internet connection , I select Ethernet Connection and the installer reboot and I get back to the starting point.
I've taken the files in your github and putted them in clover.
Can you help me ? :'(
Thanks 

ps: Sorry for my english , I'm french

**Comment by erikbdev** [comment]
You might need another AtherosE022Ethernet.kext driver.

**Comment by WaKeNighTt** [comment]
Well I think it's my network adapter who is faulty. 
He is not working anymore, even with windows.
I wil try to reinstall windows, check if it's working and then reinstall OSX.
I will give more informations when done.
