### ISSUE TITLE
Random Black Screens after boot / Thunderbolt / Misc Issues

### ISSUE THREAD

**Issue by mtotallywiredtoo** [ErrorErrorError/msi-gs65-gs75-hackintosh#13]
Hi there, 

Firstly, thanks so much for this guide! I can't believe I have a pretty much fully working os x on my gs65 8se! I have the same exact specs as you, except running 1tb ssd for windows, 2tb for mac and 32 gigs of ram. same 8750h and 2060 config. This is my first hackintosh ever, and overall I can't believe its working as well as it is, in just a few hours, thanks to your guide. 

I just wanted to share some observations with you that maybe you could shine some light on and maybe help me fix? 

Firstly, I did follow your post installation guide and that other guide, that lets me boot the EFI from the SSD rather than the hard disk. When I tried to boot up into mac right after that method, clover only showed windows options. I tried to connect the dots, and replaced the EFI folder from that guide, with the EFI folder that was on the USB stick, that I created from your guide. Voila...got the options to boot into mac. I thought I should preface that, just in case I did something wrong that is affecting these few other issues I am seeing. 

1. The most troubling issue I would say is that sometimes when I boot from clover into os x
as soon as the apple loading bar begins to load, it will black screen. Now that's not to say it didn't actually boot into mac. When I go to hard power off the computer, I do see a glimpse of the login screen for a millisecond. 

This never happens if I clover boot from the USB. and also, in my not-so scientific testing, it only happened after I put the SSDT-XOCI.aml in the patched folder. That said, I've also tested back and forth after the fact, removing that XOCI.aml out, and still able to replicate black screen. Also thought I had fixed it when I set my SMBios to Macbook Pro 15,2 in Clover Configurator, but it still happens sometimes. I've included a zip of my whole efi folder, is there anything that stands out that I'm doing wrong? 

Also I just noticed that in the kexts / other folder all the brcm related files are already in there but I won't be getting my wifi card until Monday. Could that be the culprit? Currently, I am using a wifi dongle. and have a bluetooth dongle that I have yet to plug in. 

2. The next issue relates to thunderbolt. After install / post install thunderbolt was not working. 
I tried connecting a samsung T5 ssd as well as an external NVME enclosure. After a few attempts and a few restarts, I tried connecting a usb c hub, and reconnected the T5 as a USB A connection. That somehow worked. Thunderbolt was the deciding factor in me buying this machine over others, because I am a music producer and use Universal Audio Apollo Twin Duo Audio Interface. Surprisingly, this was also not working on the windows side and it wasn't until updating the drivers in windows and having the audio interface recognize in windows first and then restarting and booting into mac, that the mac recognizes it as a thunderbolt device. I think its related to hotplug / hotswap...don't quite understand which, but anyway, as of right now, I can't get it to be recognized on the mac side unless I load it in windows first. If I completely shut down and try to boot directly to mac, it doesn't work. And also if it is recognized, and I turn it off and back on again...it does not see it again unless I boot back into windows to have it recognize the device, and then back into mac. Also, shutting down, and booting straight into mac, with the audio thunderbolt device plugged in always gives me that black screen, but never if I load it in windows first. I did notice in your ACPI repo, that there is a SSDT-TYPC.aml, which is not mentioned in the guide but I do see it reflected in your config.plist. I've since put it into my EFI, but doesn't seem to have made any difference to this issue. 

3. As another user or two have mentioned, I do get that lag on the login screen, but from reading those issues, I wasn't clear on how to fix it? I did see in a closed issue thread this

> Also, to fix the boot glitch, try adding gfxrst=1 in your boot arguments.

Can you walk me through how and where to add that? I'm a mega noob. sorry. 

4. The trackpad lags when scrolling in google chrome or safari (only things I've tested so far) I noticed you mention something about Voodoo that you're using but didn't include in the guide, because of a kernel panic that improved your trackpad experience. Can you potentially clue me in as to how to do that on my machine? 

5. I always have to turn the brightness back up upon reboot. Not a huge issue, but any way to have it default set to full brightness? 

Again thank you again so much for your hard work and responsiveness. This machine is overall, working amazingly. If I can fix some of the above issues, I would be super grateful. 

Attachment: 
[EFI.zip](https://github.com/ErrorErrorError/msi-gs65-gs75-hackintosh/files/4050382/EFI.zip)

**Comment by erikbdev** [comment]
> 1. The most troubling issue I would say is that sometimes when I boot from clover into os x
>    as soon as the apple loading bar begins to load, it will black screen. Now that's not to say it didn't actually boot into mac. When I go to hard power off the computer, I do see a glimpse of the login screen for a millisecond.

That is an issue with Coffeelake systems and sometimes it does happen to my system but now it's every once in a while. There isn't a "clear" fix to the issue but based on what I remembered on diagnosing it has to do with the backlight control.



> Also I just noticed that in the kexts / other folder all the brcm related files are already in there but I won't be getting my wifi card until Monday. Could that be the culprit? Currently, I am using a wifi dongle. and have a bluetooth dongle that I have yet to plug in.
> 

Those drivers will not load if they don't detect the wifi card so it shouldn't be a problem.




> 1. Also, shutting down, and booting straight into mac, with the audio thunderbolt device plugged in always gives me that black screen, but never if I load it in windows first. I did notice in your ACPI repo, that there is a SSDT-TYPC.aml, which is not mentioned in the guide but I do see it reflected in your config.plist. I've since put it into my EFI, but doesn't seem to have made any difference to this issue.

Thunderbolt is very complicated in the hackintosh world. There has been attempts to fix it but it's been untested. Ideally the SSDT-TYPC.aml should activate the USB Controller of the Thunderbolt but that's as far as it can go. Hot-plugging is also an issue with thunderbolt. There is another file if you want to test out  that may fix Thunderbolt hot-plugging.

> 2\. As another user or two have mentioned, I do get that lag on the login screen, but from reading those issues, I wasn't clear on how to fix it? I did see in a closed issue thread this
>

I am still trying to fix it but the cause of it is when the SSDT-DDGPU is disabling the NVIDIA card causes the lag on the screen.

> * The trackpad lags when scrolling in google chrome or safari (only things I've tested so far) I noticed you mention something about Voodoo that you're using but didn't include in the guide, because of a kernel panic that improved your trackpad experience. Can you potentially clue me in as to how to do that on my machine?
> *

Try updating [VoodooPS2.kext](https://github.com/acidanthera/VoodooPS2/releases/tag/2.1.0) with the newest version. They improved the trackpad on the new version.



> 2\. I always have to turn the brightness back up upon reboot. Not a huge issue, but any way to have it default set to full brightness?

That means that your native NVRAM does not work on macOS. You will have to emulate the NVRAM and I will upload the guide with how to have emulated nvram.

**Comment by erikbdev** [comment]
> Thunderbolt is very complicated in the hackintosh world. There has been attempts to fix it but it's been untested. Ideally the SSDT-TYPC.aml should activate the USB Controller of the Thunderbolt but that's as far as it can go. Hot-plugging is also an issue with thunderbolt. There is another file if you want to test out that may fix Thunderbolt hot-plugging.
> 
> >

Actually I found a driver which attempts to fix this issue by powering on the Thunderbolt all the time, as how macOS works, but I have no thunderbolt port. Link [here](https://github.com/hackintosh-stuff/macOS-IOElectrify)

**Comment by mtotallywiredtoo** [comment]
Thanks so very much! I will try the new voodoo and get back to you. 
Also, I'm such a dummy when it comes to this stuff...how might I implement that thunderbolt fix to your configuration?

**Comment by erikbdev** [comment]
[IOElectrify.kext.zip](https://github.com/ErrorErrorError/msi-gs65-gs75-hackintosh/files/4050913/IOElectrify.kext.zip)
Extract the file and copy IOElectrify.kext to your clover/kexts/others/ folder. Also, remove the SSDT-TYPC.aml and let me know if it works.

**Comment by mtotallywiredtoo** [comment]
> That is an issue with Coffeelake systems and sometimes it does happen to my system but now it's every once in a while. There isn't a "clear" fix to the issue but based on what I remembered on diagnosing it has to do with the backlight control.

Yeah. I've noticed if I'm booting from a shutdown machine, it will black screen. If I then hard reset from there, it won't do it. Also It never black screens if I boot from the USB clover setup...but why is that I wonder? Is it because none of those patched files are applied at boot? Which is strange because everything still works as if they have been applied. 

> Try updating [VoodooPS2.kext](https://github.com/acidanthera/VoodooPS2/releases/tag/2.1.0) with the newest version. They improved the trackpad on the new version.

I tried this and unfortunately it killed the trackpad. Wouldn't work at all. I just replaced the one that was originally in there. rebooted and tried a few times. Did you replace it on your system and if so does it work? 

> That means that your native NVRAM does not work on macOS. You will have to emulate the NVRAM and I will upload the guide with how to have emulated nvram.

Thanks. Looking forward to that. 

> [IOElectrify.kext.zip](https://github.com/ErrorErrorError/msi-gs65-gs75-hackintosh/files/4050913/IOElectrify.kext.zip)
> Extract the file and copy IOElectrify.kext to your clover/kexts/others/ folder. Also, remove the SSDT-TYPC.aml and let me know if it works.

I tried this and unfortunately it didn't work. I wonder if it is just wrongly configured for our particular system. As useless as I am, I wouldn't know what to or how to modify it to be correct. I was just supposed to drag it into the kexts / other folder right? Did anything need to be changed in config.plist? 

One final thing I've noticed is that the battery does not charge? When I first loaded the system, it stayed at 96%, unplugged it to test the battery for a little while and now it's staying at 91%. Clicking on the battery icon on the top right of the screen also says "Battery Not Charging" Did I do something wrong? Do I need to charge it to 100% in windows first for it to see that? 

Thanks again for all your help thus far.

**Comment by erikbdev** [comment]
> Yeah. I've noticed if I'm booting from a shutdown machine, it will black screen. If I then hard reset from there, it won't do it. Also It never black screens if I boot from the USB clover setup...but why is that I wonder? Is it because none of those patched files are applied at boot? Which is strange because everything still works as if they have been applied.
> 

It's a common issue for Coffelake systems. For more info you can read [here](https://www.tonymacx86.com/threads/bug-black-screen-3-minutes-after-booting-coffeelake-uhd-630.261131/).


> I tried this and unfortunately it killed the trackpad. Wouldn't work at all. I just replaced the one that was originally in there. rebooted and tried a few times. Did you replace it on your system and if so does it work?
> 
>
Try downloading VoodooI2C.kext and VoodooI2CHID.kext from [here](https://github.com/alexandred/VoodooI2C/releases/tag/2.3) and place them in your clover/kexts/others/ folder and see if trackpad works. If you get a kernel panic, ie system crashes on boot, then you will need a script to load the kexts at login (which is what I am doing as of now).


> I tried this and unfortunately it didn't work. I wonder if it is just wrongly configured for our particular system. As useless as I am, I wouldn't know what to or how to modify it to be correct. I was just supposed to drag it into the kexts / other folder right? Did anything need to be changed in config.plist?

Dang, I thought that would of worked. Thunderbolt is the only issue that the hackintosh community is struggling to fix, specifically hot-plugging. The only way to actually get your thunderbolt to work is by booting into Windows, plugging in the Thunderbolt device, and without unplugging the thunderbolt , restart to macOS.

> One final thing I've noticed is that the battery does not charge? When I first loaded the system, it stayed at 96%, unplugged it to test the battery for a little while and now it's staying at 91%. Clicking on the battery icon on the top right of the screen also says "Battery Not Charging" Did I do something wrong? Do I need to charge it to 100% in windows first for it to see that?

It should charge. You might need to update the VirtualSMC.kext and SMCBatteryManager,kext

**Comment by mtotallywiredtoo** [comment]
> Try downloading VoodooI2C.kext and VoodooI2CHID.kext from [here](https://github.com/alexandred/VoodooI2C/releases/tag/2.3) and place them in your clover/kexts/others/ folder and see if trackpad works. If you get a kernel panic, ie system crashes on boot, then you will need a script to load the kexts at login (which is what I am doing as of now).
> 
> >

Okay I will try this and report back to you. Oh one last thing, before I add these to the kexts folder, should I remove Voodoo PS2 or leave it in there? Thanks!


> Dang, I thought that would of worked. Thunderbolt is the only issue that the hackintosh community is struggling to fix, specifically hot-plugging. The only way to actually get your thunderbolt to work is by booting into Windows, plugging in the Thunderbolt device, and without unplugging the thunderbolt , restart to macOS.
> 
> >

Yep, as of right now, I'm thankful that at least this workaround works. I will try it one last time as I didn't have too much time to test it thoroughly. I wonder if maybe leaving the typc.aml and including the kext could help? 


> It should charge. You might need to update the VirtualSMC.kext and SMCBatteryManager,kext

I will try again. I did read somewhere that it not charging up to 100% is actually a built in MSI protection for the battery, and that the percentage needs to drop below a certain amount (If i remember, below 90%) before it will charge again. Also, if I do need to update, where do I get the updated files from? I will also report back to you on this. 

Thanks again for your quick responses. It has been really helpful!

**Comment by mtotallywiredtoo** [comment]
> Try downloading VoodooI2C.kext and VoodooI2CHID.kext from [here](https://github.com/alexandred/VoodooI2C/releases/tag/2.3) and place them in your clover/kexts/others/ folder and see if trackpad works. If you get a kernel panic, ie system crashes on boot, then you will need a script to load the kexts at login (which is what I am doing as of now).
> 
> >

Oh one last thing, before I add these to the kexts folder, should I remove Voodoo PS2 or leave it in there? Thanks!

**Comment by mtotallywiredtoo** [comment]
> Try downloading VoodooI2C.kext and VoodooI2CHID.kext from [here](https://github.com/alexandred/VoodooI2C/releases/tag/2.3) and place them in your clover/kexts/others/ folder and see if trackpad works. If you get a kernel panic, ie system crashes on boot, then you will need a script to load the kexts at login (which is what I am doing as of now).

So I just tried this (without removing VoodooPS2...wasn't sure If I was supposed to do that first) and I was black screening upon every reboot. That's probably the crash or kernel panic happening? Let me know if I should've done differently

> It should charge. You might need to update the VirtualSMC.kext and SMCBatteryManager,kext

Also, it is charging now. I did have to drop down to 89 before charging again, so maybe it is that built in MSI battery protection thing happening. 

Many thanks :)

**Comment by mtotallywiredtoo** [comment]
Quick question, since we have virtually the same machine, have you ever run benchmarks on yours?  LIke geekbench? Does turboboost work out of the box in this build? I'm wondering if there might be anyway to overclock the cpu or at least reach its full potential. Thanks again.

**Comment by mtotallywiredtoo** [comment]
> Quick question, since we have virtually the same machine, have you ever run benchmarks on yours? LIke geekbench? Does turboboost work out of the box in this build? I'm wondering if there might be anyway to overclock the cpu or at least reach its full potential. Thanks again.

Hahaha. Stupid me. I had used Geekbench 5 instead of 4, so the numbers were so low I was like WTF? This machine outperforms the 2018 MBPs. And seems to Turbo boost almost to 4ghz. 

Thanks again for helping make my very first hackintosh build a very very positive one and being so responsive and helpful with all of my questions. 

![Screen Shot 2020-01-15 at 12 21 43 AM](https://user-images.githubusercontent.com/49461123/72481551-df720580-37c8-11ea-90a7-a8ad0acbefa2.png)

**Comment by erikbdev** [comment]
> Okay I will try this and report back to you. Oh one last thing, before I add these to the kexts folder, should I remove Voodoo PS2 or leave it in there? Thanks!

No. You need VoodooPS2 in order for the keyboard to work.





> I will try again. I did read somewhere that it not charging up to 100% is actually a built in MSI protection for the battery, and that the percentage needs to drop below a certain amount (If i remember, below 90%) before it will charge again. Also, if I do need to update, where do I get the updated files from? I will also report back to you on this.

Yeah it has to do with the battery protection.



> So I just tried this (without removing VoodooPS2...wasn't sure If I was supposed to do that first) and I was black screening upon every reboot. That's probably the crash or kernel panic happening? Let me know if I should've done differently 

Yup your computer does have kernel panic. I have a workaround which runs a script on boot up and loads the kext and you can get native gestures working if you are interested.




> Quick question, since we have virtually the same machine, have you ever run benchmarks on yours? LIke geekbench? Does turboboost work out of the box in this build? I'm wondering if there might be anyway to overclock the cpu or at least reach its full potential. Thanks again.

I did ran a benchmark but I forgot the score of it but you can try CPUFriend.kext to increase clock speeds.

**Comment by mtotallywired** [comment]
> Yup your computer does have kernel panic. I have a workaround which runs a script on boot up and loads the kext and you can get native gestures working if you are interested.

Thanks, definitely interested in this workaround! Please let me know how to do it if possible. Do you notice much better trackpad performance with it? 



> I did ran a benchmark but I forgot the score of it but you can try CPUFriend.kext to increase clock speeds.

Ooo, I would love to try this. Where can I get CPUFriend.kext from? What exactly does it do? 
Again thanks so much :)

**Comment by mtotallywiredtoo** [comment]
Please let me know when you get a chance on how I might improve my trackpad in the same way that you've outlined for your own rig. 

Also, curious as to what your battery life is like on the mac side vs windows side? Did you do any mods there? 

Thanks again

**Comment by erikbdev** [comment]
> Please let me know when you get a chance on how I might improve my trackpad in the same way that you've outlined for your own rig.

Are you currently using VooodooInput?

> Also, curious as to what your battery life is like on the mac side vs windows side? Did you do any mods there?

Currently my macOS battery life has been crap. I get about 2-3 hours of battery life on macOS.

**Comment by mtotallywired** [comment]
> Try downloading VoodooI2C.kext and VoodooI2CHID.kext from [here](https://github.com/alexandred/VoodooI2C/releases/tag/2.3) and place them in your clover/kexts/others/ folder and see if trackpad works. If you get a kernel panic, ie system crashes on boot, then you will need a script to load the kexts at login (which is what I am doing as of now).

Hey Thanks for getting back to me. Previously, you had asked me to try what I quoted above. Is that voodoo input? If so, my computer kernel panics when I include those. 

> Yup your computer does have kernel panic. I have a workaround which runs a script on boot up and loads the kext and you can get native gestures working if you are interested.

If that is the case, you had mentioned some type of script / workaround. Is this still what you're currently doing? If so how can I apply your script to my computer? Or open to any other instruction you may have as to how to improve it. 

Thanks again in advance. 

Lastly:
Regarding battery life. I had made some changes on the windows side such as lowering the keyboard brightness, some very minor bios modifications, and using throttlestop and modifying some settings in windows power settings, like eco-mode when on battery and all that. I basically just followed tutorials and stuff I found online in how to maximize battery life on the gs65.  I don't know if I'm bugging, but I think they might carry over once you boot into mac. Would that make any sense? Also one of the biggest battery saving things I've seen on the mac side was lowering the screen refresh rate from 120hz to 60hz in the display settings. I'm now getting at least 5 hours

**Comment by erikbdev** [comment]
> If that is the case, you had mentioned some type of script / workaround. Is this still what you're currently doing? If so how can I apply your script to my computer? Or open to any other instruction you may have as to how to improve it.

Just update VoodooPS2 to the latest version and there shouldn't be anymore kernel panics.

**Comment by mtotallywired** [comment]
Yes! That did it! :D Trackpad is so much better now! Just to recap for anyone who is also looking to do this you need to get the latest VoodooPS2 from https://github.com/acidanthera/VoodooPS2/releases

And also  VoodooI2C.kext and VoodooI2CHID.kext from  
https://github.com/alexandred/VoodooI2C/releases/tag/2.3
and place them all in your clover/kexts/others/ folder and restart. Voila! 

Thanks again for all your help!

**Comment by handzup** [comment]
> 1. The most troubling issue I would say is that sometimes when I boot from clover into os x
>    as soon as the apple loading bar begins to load, it will black screen. Now that's not to say it didn't actually boot into mac. When I go to hard power off the computer, I do see a glimpse of the login screen for a millisecond.

Hi
Have you solved your display backlight issue?
I can't solve this problem in any way.Waiting 3 minutes is very long

**Comment by erikbdev** [comment]
> Hi
> Have you solved your display backlight issue?
> I can't solve this problem in any way.Waiting 3 minutes is very long

I advise to use OpenCore and the latest whatevergreen.kext with the SSDT-PLNF-CFLK.aml hotpatch.
