### ISSUE TITLE
BCM94352Z(dw1560) does not work on gs 75

### ISSUE THREAD

**Issue by lilmik** [ErrorErrorError/msi-gs65-gs75-hackintosh#14]
the wifi module can not be recognized on both windows 10 and hackintosh.

**Comment by erikbdev** [comment]
> the wifi module can not be recognized on both windows 10 and hackintosh.

After researching, the MSI GS75 does not support non CNVi M.2 chips. But, on my system (MSI GS65) has the CNVi M.2 also but it works with BCM94232Z.

**Comment by erikbdev** [comment]
BTW, you could try using itlwm.kext and use your Intel card rather than BCM cards.
