### ISSUE TITLE
Trackpad not working for gs65 8se

### ISSUE THREAD

**Issue by tuotuoZ** [ErrorErrorError/msi-gs65-gs75-hackintosh#17]
Hi ErrorErrorError, the only thing not working for my set up is the trackpad. I guess it's because the newer version of GS65 are using I2C trackpad?

**Comment by erikbdev** [comment]
> Hi ErrorErrorError, the only thing not working for my set up is the trackpad. I guess it's because the newer version of GS65 are using I2C trackpad?

If you're using the latest version of VoodooPS2 by acidanthera, then you will need VooodooInput for your trackpad to work. You can also try VoodooI2C, which performs better than VoodooInput, but it does crash at startup.

**Comment by tuotuoZ** [comment]
Hi, I just tried VoodooInput. I put the .kext file under Clover/kexts/others folder. Everything is working just fine! Thanks a lot!
