### ISSUE TITLE
GS65-9SE replaced dw1560 on Catalina can't connect airpods2

### ISSUE THREAD

**Issue by jryhonor** [ErrorErrorError/msi-gs65-gs75-hackintosh#18]
Firstly, thank for your great job on this series. I use your efi on my 9se-1091(replaced dw1560), almost 99% worked. 
Only one issue for me is airpods can't be connected, every first time I try to connect the airpods2 when startup the system, it can be connected for a second and lost, then no longer can be connected any more.
Could you give me any solution for this issue please? Thank you for every work you did on this laptop！

**Comment by jryhonor** [comment]
BTW, airpods2 can be connected in windows 10 by dw1560.

**Comment by erikbdev** [comment]
Update the AirportBrcmFixUp next to the latest version

**Comment by igitfisher** [comment]
> Firstly, thank for your great job on this series. I use your efi on my 9se-1091(replaced dw1560), almost 99% worked.
> Only one issue for me is airpods can't be connected, every first time I try to connect the airpods2 when startup the system, it can be connected for a second and lost, then no longer can be connected any more.
> Could you give me any solution for this issue please? Thank you for every work you did on this laptop！

Hi Sir

I searched all over the internet and so excited to find your share here, since I just ordered a new MSI GS65 9 SE, and because I have to use Mac for working and Linux/Win for hobby, I try to install this as well.

I’m using Mac for years, but new to Hackintosh, reviewed some articles try to understand the essentials of install Mac at Non-Apple machine, I know how difficult to get all matching firmwares and killing issues.

May I have your sharing on the experience and better the EFi and other necessary files to run this machine? Sincerely appreciate your kindness in advance.

My GS65 major modules are: i7-9750H/RTX2060/Killer E2500 Ethernet + Intel 9560 Wireless

my email is ifanzhang@icloud.com, wish to get your reply here or through email.

Thanks and best regards.
Frank

**Comment by jryhonor** [comment]
> Update the AirportBrcmFixUp next to the latest version

thanks for your reply, I will try it.

**Comment by erikbdev** [comment]
> > Firstly, thank for your great job on this series. I use your efi on my 9se-1091(replaced dw1560), almost 99% worked.
> > Only one issue for me is airpods can't be connected, every first time I try to connect the airpods2 when startup the system, it can be connected for a second and lost, then no longer can be connected any more.
> > Could you give me any solution for this issue please? Thank you for every work you did on this laptop！
> 
> Hi Sir
> 
> I searched all over the internet and so excited to find your share here, since I just ordered a new MSI GS65 9 SE, and because I have to use Mac for working and Linux/Win for hobby, I try to install this as well.
> 
> I’m using Mac for years, but new to Hackintosh, reviewed some articles try to understand the essentials of install Mac at Non-Apple machine, I know how difficult to get all matching firmwares and killing issues.
> 
> May I have your sharing on the experience and better the EFi and other necessary files to run this machine? Sincerely appreciate your kindness in advance.
> 
> My GS65 major modules are: i7-9750H/RTX2060/Killer E2500 Ethernet + Intel 9560 Wireless
> 
> my email is [ifanzhang@icloud.com](mailto:ifanzhang@icloud.com), wish to get your reply here or through email.
> 
> Thanks and best regards.
> Frank

I have an EFI uploaded on GitHub which you can use and keep in mind stock wifi card will NOT work, only bluetooth unless if you change with a DW1560.

**Comment by igitfisher** [comment]
> > > Firstly, thank for your great job on this series. I use your efi on my 9se-1091(replaced dw1560), almost 99% worked.
> > > Only one issue for me is airpods can't be connected, every first time I try to connect the airpods2 when startup the system, it can be connected for a second and lost, then no longer can be connected any more.
> > > Could you give me any solution for this issue please? Thank you for every work you did on this laptop！
> > 
> > 
> > Hi Sir
> > I searched all over the internet and so excited to find your share here, since I just ordered a new MSI GS65 9 SE, and because I have to use Mac for working and Linux/Win for hobby, I try to install this as well.
> > I’m using Mac for years, but new to Hackintosh, reviewed some articles try to understand the essentials of install Mac at Non-Apple machine, I know how difficult to get all matching firmwares and killing issues.
> > May I have your sharing on the experience and better the EFi and other necessary files to run this machine? Sincerely appreciate your kindness in advance.
> > My GS65 major modules are: i7-9750H/RTX2060/Killer E2500 Ethernet + Intel 9560 Wireless
> > my email is [ifanzhang@icloud.com](mailto:ifanzhang@icloud.com), wish to get your reply here or through email.
> > Thanks and best regards.
> > Frank
> 
> I have an EFI uploaded on GitHub which you can use and keep in mind stock wifi card will NOT work, only bluetooth unless if you change with a DW1560.

Hi 

Thanks for the caring reply, I’m going to purchase a new BCM94352z/DW1560 to replace the default Intel 9560 wireless module.

You said already Have EFI uploaded on GitHub, my concern is that these drivers are designed for GS65 8SE, while I will have a 9SE (tomorrow), do I need specifically change anything during the guided steps? Because the 9SE have most latest hardwares, such as RTX2060/Killer E2500/etc...

I’m sorry asked so detail and may because of I have no experience at Hackintosh yet.

Anyway, thanks for your help

**Comment by igitfisher** [comment]
> > > Firstly, thank for your great job on this series. I use your efi on my 9se-1091(replaced dw1560), almost 99% worked.
> > > Only one issue for me is airpods can't be connected, every first time I try to connect the airpods2 when startup the system, it can be connected for a second and lost, then no longer can be connected any more.
> > > Could you give me any solution for this issue please? Thank you for every work you did on this laptop！
> > 
> > 
> > Hi Sir
> > I searched all over the internet and so excited to find your share here, since I just ordered a new MSI GS65 9 SE, and because I have to use Mac for working and Linux/Win for hobby, I try to install this as well.
> > I’m using Mac for years, but new to Hackintosh, reviewed some articles try to understand the essentials of install Mac at Non-Apple machine, I know how difficult to get all matching firmwares and killing issues.
> > May I have your sharing on the experience and better the EFi and other necessary files to run this machine? Sincerely appreciate your kindness in advance.
> > My GS65 major modules are: i7-9750H/RTX2060/Killer E2500 Ethernet + Intel 9560 Wireless
> > my email is [ifanzhang@icloud.com](mailto:ifanzhang@icloud.com), wish to get your reply here or through email.
> > Thanks and best regards.
> > Frank
> 
> I have an EFI uploaded on GitHub which you can use and keep in mind stock wifi card will NOT work, only bluetooth unless if you change with a DW1560.

Thanks so much, you really did great job here.

After carefully read all the information in README file, I would like to try first and then maybe come back in case any issues can not resolve. 
I’m still a bit unclear about Clover, read dozen articles and get too many different voices, will try, I’m going to setup Win(gaming)/MacOS(working)/Manjaro Linux(Hobby and coding)/ as triple boot.

I should receive my new GS65 9SE tomorrow and also will order a DW1560 card to replace the default Intel 9570.

**Comment by erikbdev** [comment]
Clover is a bootloader that can be used to boot windows and Linux, but is designed to boot specifically macOS

**Comment by jryhonor** [comment]
> > > > Firstly, thank for your great job on this series. I use your efi on my 9se-1091(replaced dw1560), almost 99% worked.
> > > > Only one issue for me is airpods can't be connected, every first time I try to connect the airpods2 when startup the system, it can be connected for a second and lost, then no longer can be connected any more.
> > > > Could you give me any solution for this issue please? Thank you for every work you did on this laptop！
> > > 
> > > 
> > > Hi Sir
> > > I searched all over the internet and so excited to find your share here, since I just ordered a new MSI GS65 9 SE, and because I have to use Mac for working and Linux/Win for hobby, I try to install this as well.
> > > I’m using Mac for years, but new to Hackintosh, reviewed some articles try to understand the essentials of install Mac at Non-Apple machine, I know how difficult to get all matching firmwares and killing issues.
> > > May I have your sharing on the experience and better the EFi and other necessary files to run this machine? Sincerely appreciate your kindness in advance.
> > > My GS65 major modules are: i7-9750H/RTX2060/Killer E2500 Ethernet + Intel 9560 Wireless
> > > my email is [ifanzhang@icloud.com](mailto:ifanzhang@icloud.com), wish to get your reply here or through email.
> > > Thanks and best regards.
> > > Frank
> > 
> > 
> > I have an EFI uploaded on GitHub which you can use and keep in mind stock wifi card will NOT work, only bluetooth unless if you change with a DW1560.
> 
> Thanks so much, you really did great job here.
> 
> After carefully read all the information in README file, I would like to try first and then maybe come back in case any issues can not resolve.
> I’m still a bit unclear about Clover, read dozen articles and get too many different voices, will try, I’m going to setup Win(gaming)/MacOS(working)/Manjaro Linux(Hobby and coding)/ as triple boot.
> 
> I should receive my new GS65 9SE tomorrow and also will order a DW1560 card to replace the default Intel 9570.

I have replied you by email, you can check it anytime.
