### ISSUE TITLE
Stuck at Apple logo

### ISSUE THREAD

**Issue by troyjamz** [ErrorErrorError/msi-gs65-gs75-hackintosh#20]
Hi. First of all I'd like to thank you for sharing this! My laptop is a Msi Gs75 stealth 85F and
![15870589414161841783383419594372](https://user-images.githubusercontent.com/46408894/79488895-c290dc80-801a-11ea-9f0b-e329473149dd.jpg)
 I have followed your instructions perfectly without any issues until I got to the part where I first open Clover to Boot Install macOS Catalina (10.15.4)

The apple logo appears and then it gets stuck.

I have now rebooted and attempted to install in verbose mode so I can see the errors but I don't know what to do with them. Do you think you can assist me with resolving this?

**Comment by erikbdev** [comment]
> I have now rebooted and attempted to install in verbose mode so I can see the errors but I don't know what to do with them. Do you think you can assist me with resolving this?

How long did you waited after the apple logo showed up? It does usually take long the first time booting after installation. Also, those are new errors from 10.15.4, so I would recommend downgrading to 10.15.3 or lower to see if you're able to boot up. I haven't really been using Clover Bootloader since the whole OpenCore seems to be better than Clover, but I will check it out on my end.

**Comment by erikbdev** [comment]
Closing due to no response.

**Comment by handzup** [comment]
> How long did you waited after the apple logo showed up? It does usually take long the first time booting after installation. Also, those are new errors from 10.15.4, so I would recommend downgrading to 10.15.3 or lower to see if you're able to boot up. I haven't really been using Clover Bootloader since the whole OpenCore seems to be better than Clover, but I will check it out on my end.

Thanks for your work.
Does OpenCore in your repository work as well as your Clover? after switching from Mojave to Catalina, I had a problem with 3 minutes of switching off the backlight and I could not solve this problem and decided to try

**Comment by erikbdev** [comment]
> Does OpenCore in your repository work as well as your Clover? after switching from Mojave to Catalina, I had a problem with 3 minutes of switching off the backlight and I could not solve this problem and decided to try

Assuming you have the exact system as my model, MSI GS65-8SE, yes however I have not updated that repository with the current config I have.

**Comment by handzup** [comment]
> > Does OpenCore in your repository work as well as your Clover? after switching from Mojave to Catalina, I had a problem with 3 minutes of switching off the backlight and I could not solve this problem and decided to try
> 
> Assuming you have the exact system as my model, MSI GS65-8SE, yes however I have not updated that repository with the current config I have.

thanks for the answer. I have a gs65 8sf model. and I think that the only difference is the GPU. It would be great to get your updated repository.

**Comment by erikbdev** [comment]
> > > Does OpenCore in your repository work as well as your Clover? after switching from Mojave to Catalina, I had a problem with 3 minutes of switching off the backlight and I could not solve this problem and decided to try
> > 
> > 
> > Assuming you have the exact system as my model, MSI GS65-8SE, yes however I have not updated that repository with the current config I have.
> 
> thanks for the answer. I have a gs65 8sf model. and I think that the only difference is the GPU. It would be great to get your updated repository.

I'll be updating it soon.

**Comment by handzup** [comment]
> > > > Does OpenCore in your repository work as well as your Clover? after switching from Mojave to Catalina, I had a problem with 3 minutes of switching off the backlight and I could not solve this problem and decided to try
> > > 
> > > 
> > > Assuming you have the exact system as my model, MSI GS65-8SE, yes however I have not updated that repository with the current config I have.
> > 
> > 
> > thanks for the answer. I have a gs65 8sf model. and I think that the only difference is the GPU. It would be great to get your updated repository.
> 
> I'll be updating it soon.

thank u so much
