### ISSUE TITLE
Stuck at 1st installation

### ISSUE THREAD

**Issue by dyoustra** [ErrorErrorError/msi-gs65-gs75-hackintosh#21]
Hi, first of all I would like to thank you for making this guide. I appreciate your continued support of it and of people having issues with it. I am using a GS65 with an RTX 2060 and 630 Integrated graphics (same as yours). If you need to know any other specs I can let you know. I ran through your guide and got stuck on the part where I am to boot into clover for the first time. When running normally without the verbose parameter, It shows the apple logo and a loading bar. After loading to about the middle of the bar, it reboots my computer. When I run it with the verbose parameter, it gives a long log before eventually rebooting. I took a video of the log if you think it could help you understand the problem. Do you know of any way to solve this?

Verbose Log: https://drive.google.com/file/d/1cdXLu4Ot1wUpxemurU1l0KpqFgDig1Q6/view?usp=sharing

**Comment by erikbdev** [comment]
Upload your EFI files and what macOS version are you trying to install?

**Comment by dyoustra** [comment]
I am trying to install Catalina, would Mojave be better?

EFI:
[EFI.zip](https://github.com/ErrorErrorError/msi-gs65-gs75-hackintosh/files/4532046/EFI.zip)

**Comment by erikbdev** [comment]
I'd recommend trying Catalina.

**Comment by dyoustra** [comment]
That should mean my EFI folder is correctly configured because I created it based on your Catalina tutorial and specifications.

**Comment by erikbdev** [comment]
> That should mean my EFI folder is correctly configured because I created it based on your Catalina tutorial and specifications.

I wont consider it as "correctly configured" since there is no way correctly do it, however it should at least work.
