### ISSUE TITLE
MSI GL63 9SDK DDGPU

### ISSUE THREAD

**Issue by svinayak780** [ErrorErrorError/msi-gs65-gs75-hackintosh#22]
So I have an MSI GL639SDK with GTX1660Ti and I need help in disabling it. I have attached my DSDT.
[DSDT.aml.zip](https://github.com/ErrorErrorError/msi-gs65-gs75-hackintosh/files/4537013/DSDT.aml.zip)

**Comment by erikbdev** [comment]
you can use my SSDT-DDGPU.aml that's on the repo to disable the GTX1660Ti.

**Comment by erikbdev** [comment]
Closed due to no response
