### ISSUE TITLE
Type-c for display is not working

### ISSUE THREAD

**Issue by abc3436645** [ErrorErrorError/msi-gs65-gs75-hackintosh#23]
Hi, since I installed the Catalina15.4, the type-c port is not working. the type-c port is working when I run maco majove14. I am looking forward to your answer. 

Best wishes,
Jianan

**Comment by erikbdev** [comment]
> Hi, since I installed the Catalina15.4, the type-c port is not working. the type-c port is working when I run maco majove14. I am looking forward to your answer. 
> 
> Best wishes,
> Jianan

Works fine on my end. I would advise and check your SSDT patches and see if they are correctly configured with your system.

**Comment by abc3436645** [comment]
I add SSDT_TYPE patches, But It is still not working.

**Comment by erikbdev** [comment]
> I add SSDT_TYPE patches, But It is still not working.

Plug a device to the USB Type C port and boot up on Windows. Restart computer and boot on macOS and let me know if it works or not.

**Comment by abc3436645** [comment]
I solved this problem by adding argv in Boot :  -liubetaall parameters.

**Comment by erikbdev** [comment]
Hm. As far as I know, there is no kext from Lilu that handles USB connection, but glad it works now.
