### ISSUE TITLE
audio sometimes doesn't load

### ISSUE THREAD

**Issue by mtotallywiredtoo** [ErrorErrorError/msi-gs65-gs75-hackintosh#25]
Hi again, 

it's been a few months now and the hackintoshed gs65 is going strong! I do have one recurring issue that I've never mentioned and wonder if maybe you could point me in the right direction for a fix. 
Sometimes when I boot (from shut down state) into Mac, my audio hasn't loaded. Icon is greyed out. Core audio is missing I think. Usually a restart or two can fix it, but wondering if this is something you might know a solution for. Thanks as always, in advance!

**Comment by erikbdev** [comment]
Are you using the latest version of AppleALC.kext? I rarely get that issue unfortunately but it’a not as common as before.

**Comment by mtotallywiredtoo** [comment]
hi again, I haven't used updated anything since I made the hackintosh late January except for the fixes for the trackpad that you recommended over the past few months. I can go ahead and try that now and report back. But you do confirm, it does happen to you?

**Comment by mtotallywiredtoo** [comment]
Unfortunately that didn't work. Gave me troubles with booting -> would boot, apple logo, go black and reboot again and was consistently no audio. I put back the old AppleALC.kext and seems I can make it come back by booting into Windows. Shutting down. f11 when I reboot and load into UEFI OS (Mac) and now my audio is back. Just wondering what the cause of it might be...

**Comment by erikbdev** [comment]
Are you still using clover or OpenCore boot loader?

**Comment by mtotallywiredtoo** [comment]
I'm using clover still

**Comment by erikbdev** [comment]
Okay, load up the new AppleALC.kext and boot with verbose and not restart on panic and upload a picture of the error

**Comment by erikbdev** [comment]
Closing due to no response.
