### ISSUE TITLE
Catalina installation crushes at 11 minutes left

### ISSUE THREAD

**Issue by Dhrhciebcy** [ErrorErrorError/msi-gs65-gs75-hackintosh#26]
Hello everyone,
I am writing about a problem that I have on my MSI GS65-9SE.

First of all, I thank @ErrorErrorError for this fantastic guide that allowed me, for the first time in 4 years, to see the MacOS installer start on a non-Apple computer.

However, when I try to install Catalina on a partition of my SSD, strange things happen: in most cases, the first part of the installation crashes with "2 minutes remaining" written on it (I read on the internet that this behavior seems to be normal, also because, on reboot, I find a new partition with MacOS);
![2 minutes left crush (probably it's normal)](https://user-images.githubusercontent.com/22133554/89104363-3d8ad100-d419-11ea-81a8-e56aeef6d7d9.jpg)
Other times, however, the installer does not have time to reach the "2 minutes" that already crashes with a particular message in the log.
![crush not normal (can't reach the remaining 2 minutes)](https://user-images.githubusercontent.com/22133554/89104397-74f97d80-d419-11ea-827f-5302cadeb5e0.jpg)
When I then restart the PC and start Disk Utility from the installation pendrive, it turns out that the space of the partition where I was tending to install Catalina is occupied at less than about 8.2 GB (which is the space occupied by the operating system), therefore a sign that the installation was literally aborted.

Considering, however, the first of the two cases, which is the most common, after the PC restarts, I choose to boot from the new partition that I created with the installation. Initially everything seems to be going well, the apple logo is shown with the loading bar and then a screen opens with the words "Installing on Apple, 11 minutes remaining" (I called Apple the new partition).

After a short time, everything crashes and, repeating the same operation, nothing changes.
![11 minutes remaining crush](https://user-images.githubusercontent.com/22133554/89104409-93f80f80-d419-11ea-90ef-4d252cb2edff.jpg)
So I'm stuck in this sort of loop and unfortunately I don't even know how to log (probably freezes immediately).
How can I do? Please help :'(
I attach photos

P. S. I'm trying to install catalina on a partition of my internal SSD, which means that it will have to be in dual boot with windows (I specify this because I don't know if it could be one of the causes of these problems).

I also tried to format this partition in extended Mac, but it doesn't work because it surely only works with APFS. Furthermore, I had no problems with the creation of the installation pendrive as my pc seems practically identical to that of @ErrorErrorError 

In one of the "11 minutes remaining" crush I also surprisingly found the partition destroyed after restarting the pc
![surprise partition destroyed after one of the crushes with 11 minutes remaining](https://user-images.githubusercontent.com/22133554/89104484-fb15c400-d419-11ea-84f7-dbcf8df5fcaa.jpg)

**Comment by erikbdev** [comment]
> Hello everyone,
> 
> I am writing about a problem that I have on my MSI GS65-9SE.
> 
> 
> 
> First of all, I thank @ErrorErrorError for this fantastic guide that allowed me, for the first time in 4 years, to see the MacOS installer start on a non-Apple computer.
> 
> 
> 
> However, when I try to install Catalina on a partition of my SSD, strange things happen: in most cases, the first part of the installation crashes with "2 minutes remaining" written on it (I read on the internet that this behavior seems to be normal, also because, on reboot, I find a new partition with MacOS);
> 
> ![2 minutes left crush (probably it's normal)](https://user-images.githubusercontent.com/22133554/89104363-3d8ad100-d419-11ea-81a8-e56aeef6d7d9.jpg)
> 
> Other times, however, the installer does not have time to reach the "2 minutes" that already crashes with a particular message in the log.
> 
> ![crush not normal (can't reach the remaining 2 minutes)](https://user-images.githubusercontent.com/22133554/89104397-74f97d80-d419-11ea-827f-5302cadeb5e0.jpg)
> 
> When I then restart the PC and start Disk Utility from the installation pendrive, it turns out that the space of the partition where I was tending to install Catalina is occupied at less than about 8.2 GB (which is the space occupied by the operating system), therefore a sign that the installation was literally aborted.
> 
> 
> 
> Considering, however, the first of the two cases, which is the most common, after the PC restarts, I choose to boot from the new partition that I created with the installation. Initially everything seems to be going well, the apple logo is shown with the loading bar and then a screen opens with the words "Installing on Apple, 11 minutes remaining" (I called Apple the new partition).
> 
> 
> 
> After a short time, everything crashes and, repeating the same operation, nothing changes.
> 
> ![11 minutes remaining crush](https://user-images.githubusercontent.com/22133554/89104409-93f80f80-d419-11ea-90ef-4d252cb2edff.jpg)
> 
> So I'm stuck in this sort of loop and unfortunately I don't even know how to log (probably freezes immediately).
> 
> How can I do? Please help :'(
> 
> I attach photos
> 
> 
> 
> P. S. I'm trying to install catalina on a partition of my internal SSD, which means that it will have to be in dual boot with windows (I specify this because I don't know if it could be one of the causes of these problems).
> 
> 
> 
> I also tried to format this partition in extended Mac, but it doesn't work because it surely only works with APFS. Furthermore, I had no problems with the creation of the installation pendrive as my pc seems practically identical to that of @ErrorErrorError 
> 
> 
> 
> In one of the "11 minutes remaining" crush I also surprisingly found the partition destroyed after restarting the pc
> 
> ![surprise partition destroyed after one of the crushes with 11 minutes remaining](https://user-images.githubusercontent.com/22133554/89104484-fb15c400-d419-11ea-84f7-dbcf8df5fcaa.jpg)

The guide I have is old. I would advise to instead of using clover, to use OpenCore, which fixes a lot of issues Clover has and it follows more on what an native Mac would do in regards to boot loading.

Also, are you installing macOS on a Samsung hard drive/ssd? I've heard a couple of issues with macOS and Samsung ssd si I would recommend to update the ssd to the latest firmware.

Another thing, are you installing macOS on the same drive as windows? If so, that would most likely to be the cause of your issue.

**Comment by Dhrhciebcy** [comment]
Hi @ErrorErrorError ,
thanks for the advice of OpenCore: I didn't know it, I will inquire.

As for my SSD, yes, it's a Samsung and, as you said I could try updating the firmware, I thought I'd try to install MacOS first on a pendrive and see what happens: in theory, if on the pendrive I will have the same problems, then I don't think it's an SSD problem.
If, instead, it should be successful, then the remaining hypotheses will be two: MacOS does not want Windows or the SSD is problematic. At that point I will see how to update the firmware
Thanks for coming to my rescue
I will let you know

**Comment by Dhrhciebcy** [comment]
Hi @ErrorErrorError ,
the operation was successful and Catalina was installed perfectly on an external pendrive! (except the fact that it crashes for a few minutes without reason)
So the two hypotheses described above remain: tomorrow I will try to update the firmware of the SSD and I hope to change something (in positive)
I will write about further updates on the situation

**Comment by Dhrhciebcy** [comment]
Hi @ErrorErrorError ,
I officially communicate that I have discovered the cause of the problem and it concerns the fact that my SSD is a Samsung NVMe PM981, which is officially recognized as a **not supported** SSD for Hackintosh. It can be used by Mac, but not as a boot disk.
I thank you again for the answer you gave me and, with this, I conclude the discussion.

By the way, it was only thanks to your miraculous, albeit old according to you, guide if I now have MacOS on my MSI GS65.
You have been my salvation!!!

P. S. Catalina's crashes on the pendrive were probably due to the too low data transfer rate of the same
