### ISSUE TITLE
Do you have an OpenCore version?

### ISSUE THREAD

**Issue by annaclets** [ErrorErrorError/msi-gs65-gs75-hackintosh#27]
Hi, I have adopted your Clover EFI and very pleased with it, especially when you helped me activate eGPU on my GS75. I was wondering if you have made an OpenCore version of your EFI because I would love to adopt it too, and use it specifically for running the Big Sur public beta.

**Comment by erikbdev** [comment]
I do, however it is still a work-in-progress since OpenCore is still updating a lot of things due to Big Sur changed the way kexts are loaded in installer. I do not have Big Sur installed on my system.
