### ISSUE TITLE
BCM94352Z  wifi not working but Bluetooth work

### ISSUE THREAD

**Issue by seyhadot** [ErrorErrorError/msi-gs65-gs75-hackintosh#3]
beforei have use GS658SE but now i have switch to GS75 then i replace my old BCM94352Z to GS75 and after i have install Hackintosh wifi not working any more but bluetooth working well. then i try to test it with UBUNTU and WINDOW and the wifi still not working on both but bluetooth working for all OS. so do you have any suggestion to make it work?

**Comment by erikbdev** [comment]
Doee BIOS recognize the wifi module?

**Comment by seyhadot** [comment]
No

**Comment by seyhadot** [comment]
But when I put it back to my gs65 it's normally work

**Comment by erikbdev** [comment]
@seyhadot According to this user https://forum-en.msi.com/index.php?topic=320031.0 he found out that the GS75 laptop cannot use ither wifi chips because of intern's proprietary  CNVi that's integrated on the wifi chip. I don't think there is an option to disable CNVi so the only option is to use a usb/wifi dongle.

**Comment by seyhadot** [comment]
Oh really omg so sad to hear that but thank you so much for your answer
❤️♥️♥️

**Comment by erikbdev** [comment]
> Oh really omg so sad to hear that but thank you so much for your answer

No problem! Also, can you send a IORegistryExplorer file? reason for this is because I want to implement controlling per-key keyboard on a GS75 on macOS and I have to distinguish MSI GS65 model versus other msi per-key models.

**Comment by seyhadot** [comment]
Hi brother I have remove Mac OS just keep only window because I don't use
it anymore and so sorry for that
