### ISSUE TITLE
Have you tried Catalina with this?

### ISSUE THREAD

**Issue by skyline75489** [ErrorErrorError/msi-gs65-gs75-hackintosh#4]
I tried to upgrade from Mojave to Catalina but failed. Would love to see this working on Catalina

**Comment by erikbdev** [comment]
@skyline75489 I'm still on Mojave, but I will update to Catalina someday this week.

**Comment by skyline75489** [comment]
Nice to hear it. I'd say Hackintosh on GE63, GS65 and co are fairly easy, except the common stock Wi-Fi card problem. The Mojave I had was really stable, like 24 * 7 stable. I'll also get my hands dirty on Catalina when I'm free this week.

**Comment by erikbdev** [comment]
> Nice to hear it. I'd say Hackintosh on GE63, GS65 and co are fairly easy, except the common stock Wi-Fi card problem. The Mojave I had was really stable, like 24 * 7 stable. I'll also get my hands dirty on Catalina when I'm free this week.

I updated EFI files and README.md to support Catalina. Let me know if you have any issues.
