### ISSUE TITLE
how to disable pm981

### ISSUE THREAD

**Issue by elewen** [ErrorErrorError/msi-gs65-gs75-hackintosh#7]
I have a pm981 and other ssd，and i don‘t know how to disable pm981，can you told me？thx！

**Comment by erikbdev** [comment]
> I have a pm981 and other ssd，and i don‘t know how to disable pm981，can you told me？thx！

Disable as in prevent it from showing in macOS or Clover?

**Comment by elewen** [comment]
> > I have a pm981 and other ssd，and i don‘t know how to disable pm981，can you told me？thx！
> 
> Disable as in prevent it from showing in macOS or Clover?

Yes，disable write & read in macOS and Clover

**Comment by erikbdev** [comment]
You can use this link to prevent the pm981 from showing in your clover https://www.tonymacx86.com/threads/guide-how-to-hide-unwanted-volumes-on-clover-boot-menu.246532/

And you can use this to prevent automount in macOS https://apple.stackexchange.com/a/138497

**Comment by elewen** [comment]
> You can use this link to prevent the pm981 from showing in your clover https://www.tonymacx86.com/threads/guide-how-to-hide-unwanted-volumes-on-clover-boot-menu.246532/
> 
> And you can use this to prevent automount in macOS https://apple.stackexchange.com/a/138497

resolved, thx.
