### ISSUE TITLE
Multi-Gesture touchpad support

### ISSUE THREAD

**Issue by QiuMP** [ErrorErrorError/msi-gs65-gs75-hackintosh#8]
I found that using https://github.com/acidanthera/VoodooPS2 can achieve multi-gesture touchpad.
But I don't know why I can not use keyboard and touchpad at the same time after using it .

**Comment by erikbdev** [comment]
> I found that using https://github.com/acidanthera/VoodooPS2 can achieve multi-gesture touchpad.
> But I don't know why I can not use keyboard and touchpad at the same time after using it .

I haven't tried getting multi-gesture support from VoodooPS2, but I will try to see if I can get a chance to mess with it this week. 

Currently I have native multi-gesture support with VoodooI2C but I have to do a workaround to prevent it from having a Kernel Panic with VoodooPS2, which is why it's still not on the guide.

**Comment by QiuMP** [comment]
Thank you for your reply. 

The release of VoodooI2C has not supported 'pci8086,a36a' device which is my GS75's I2C controller. 

And in addition to the above problems, there are some inaccuracies in recognition when using VoodooPS2. So I think it may be great to use VoodooI2C to achieve native multi-gesture.
 
Thank you for your contribution, I am looking forward to your final results. 😄

**Comment by erikbdev** [comment]
> The release of VoodooI2C has not supported 'pci8086,a36a' device which is my GS75's I2C controller.

It does have support for 'pci8086,a36a' just that it's not on the latest release. You will need to build the latest commits. Reference: https://github.com/alexandred/VoodooI2C/commit/952285ddec39c4bf0608eafef173486284ea99b9

**Comment by erikbdev** [comment]
Closing due to no response.
